spring:
  cloud:
    # ==================================================================
    # Discovery configuration
    # ==================================================================
    consul:
      host: consul
  # ===================================================================
  # Datasource configuration
  # ===================================================================
  datasource:
    url: jdbc:postgresql://db-rate:5432/db-rate
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: mysecretpassword
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  # ===================================================================
  # RabbitMQ configuration
  # ===================================================================
  rabbitmq:
    host: rabbitmq
    port: 5672

