spring:
  # ===================================================================
  # Datasource configuration
  # ===================================================================
  datasource:
    url: jdbc:postgresql://localhost:5432/db-unit
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: mysecretpassword
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  port: 8083

file:
  upload:
    unit-image: units/:unitId/images