spring:
  # ===================================================================
  # Datasource configuration
  # ===================================================================
  datasource:
    url: jdbc:postgresql://localhost:5432/db-task
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: mysecretpassword
server:
  port: 8085

file:
  upload:
    root: ${user.home}/Projects/xStay/upload-folder
    incident-image: ${file.upload.root}/incidents/:incidentId
