spring:
  cloud:
    # ==================================================================
    # Discovery configuration
    # ==================================================================
    consul:
      host: consul
  # ===================================================================
  # RabbitMQ configuration
  # ===================================================================
  rabbitmq:
    host: rabbitmq
    port: 5672