spring:
  cloud:
    # ==================================================================
    # Discovery configuration
    # ==================================================================
    consul:
      host: consul
  # ===================================================================
  # Datasource configuration
  # ===================================================================
  datasource:
    url: jdbc:postgresql://db-media:5432/db-media
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: mysecretpassword
  # ===================================================================
  # RabbitMQ configuration
  # ===================================================================
  rabbitmq:
    host: rabbitmq
    port: 5672

file:
  upload:
    root: ./Projects/xStay/upload-folder